import Head from "next/head";
import Image from "next/image";
import Header from "../components/header";



export default function Home() {
  return (
    <div>
      <Head>
        <title>Nulu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>My Next Nulu App
      <Header/>

      </main>
    </div>
  );
}
